#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
SJB
Updated Jun 2024

Sample File showing some of the FlorPy functionality for Carbon Monosulfide (CS)

This script shows how to run the case of CS where the ground state, X1Sigma, is thermalized and described by a Boltzmann distribution.

First, the user must run the equilibrium case to define the necessary arrays and generate the proper internal indexing.

Then, the user runs the thermalized model. 

"""
import os
cwd = os.getcwd()
os.chdir('..')
from fluor_dict_v05152024 import *
from molecular_utils_florpy import *
#Output file for the computed g-factors:
gfac_file = 'CS_testrun'
#Output Format:
#   Wavelength (air nm (rest))   |  Wavelength (vacuum nm (rest))    |   g-factor (J/s/mol)
element_string = 'CS'
#Lines and Level input files:
levs_file = 'CS_ens_trimmed.txt'
lines_file = 'CS_trs_trimmed.txt'
# The ECO(TR) and ECO+ models can be run by simply swapping the filenames in variables levs_file and lines_file to their respective versions.
# Note: It is advised NOT to mix versions.
#Define orbital parameters:
solar_dist = 1 # heliocentric distance in Astronomical Units
obj_vel = 0    # heliocentric velocity in km/s
geo_vel = 0    # geocentric velocity in km/s
geo_dist = 1   # geocentric distance; 1AU. Not currently used.
orbital_conds = [solar_dist,obj_vel, geo_dist,geo_vel]
#Unique identifier string for this model with these orbital conditions:
orbit_id = 'co+'     #unique string identifier for the run; indicates orbital conditions.
#Radiation field file; 2column format: Wavelength (vac nm) | flux (W / m^2 / nm)
radiation_field = '0-14000_vac.txt'
#Parameter for controlling line profile for all calcs:
prof = 'delta'
#If one wants to use a doppler line profile, the following two parameters must be passed to load_orbit_data:
temp_comet = 279 * (1/np.sqrt(solar_dist)) #Kelvin; comet temperature for doppler profiles
emitter_mass = 7.31e-26 #Mass of CS in kg; only required if using profile = 'doppler'

"""
FlorPy calculations are broken into several sequential steps. They are as follows:
    build_model() : Define a dict structure to hold the model
    add_element_to_model() : Define a dictionary entry for your unique run(s)
    load_nist_data() : Load the lines/levels files into the dictionary
    load_orbit_data(): This loads in details about the heliocentric distance / velocity (see above) into the dict structure
    define_rad_fields() : Define & load the radiation field to be used into the dict structure
    generate_fluxes_general() : A generalized function that computes the pumping rates for all included lines:
    calculate_pops_and_gfactors() : The workhorse of FlorPy. This function will generate the relevant matrices, invert them,
    and compute the level populations &  g-factors
    
    Sample ways to grab this data from the dict structure are provided.
    Sample documentation is in preparation.

    To run FlorPy in the time-dependent mode, many of the functions are identical. Only one function
    is different when running time-dependently, which is the matrix solver + gfactor calculation. The sytnax below
    will calculate the level populations and g-factors time-dependently.
    For ease of operation, I recommend running the equilibrium version first so that defining
    some of the necessary arrays is easier.

"""
#First, we build FlorPy and run the equilibrium version:
flor = build_model()
flor = add_element_to_model(flor, element_string)
os.chdir('../input_files/carbon_monosulfide/')
flor = load_nist_data(flor,element_string,lines_file, levs_file)
os.chdir('../../solar_spectra/')
flor = define_rad_fields(flor,element_string,rad_source='user',radfiles=[radiation_field], vac_or_air = ['vac'])
flor = load_orbit_data(flor,element_string,orbit_id,orbital_conds,t_comet = temp_comet, m_species = emitter_mass)
flor = generate_fluxes_general(flor, element_string, orbit_id, rad_choice = 'user', profiles=prof)
flor = calculate_pops_and_gfactors(flor,element_string,orbit_id)#
os.chdir(cwd)
# We copy the equilibrium gfactors for later:
equilibrium_gfacs = np.copy(flor[element_string][orbit_id]['outputs']['gfactors'])

#For molecules, we need to run two processing functions before running the constrained (thermalized) models:
flor = separate_vib_bands(flor,element_string,orbit_id)
flor = parse_states(flor, element_string)

#One can use both vibrational and rotational temperatures, and assume "LTE" by just setting them equal. Here we use Tvib=Trot=70 for convenience:
rot_temp = 70 #Kelvin
vib_temp = 70 #Kelvin
lte_temp = 70 #Kelvin
#We grab the indices for all of the levels belonging to X1Sigma. These were generated by parse_states:
constrained_level_indices = flor[element_string]['electronic_vib_inds']['X']['electronic_indices'][0] #This grabs all of the level indices in X1Sigma v=0

# Indices for individual vibrational bands are stored in:
# v=0:   flor[element_string]['electronic_vib_inds']['X']['vib_levels']['indices'][0]
# v=1:   flor[element_string]['electronic_vib_inds']['X']['vib_levels']['indices'][1]
# and so on...
#
#   Pass these indices into calculate_pops_and_gfactors_with_thermalized_states() with a rotational and/or vibrational temperature
#   to constrain them via a boltzmann distribution. If Trot=Tvib, this is just LTE. 
flor = calculate_pops_and_gfactors_with_thermalized_states(flor,element_string,orbit_id,constrained_level_indices,vib_temp,rot_temp)  
#Grab the g-factors from the outputs:
gfacs = flor[element_string][orbit_id]['outputs']['gfactors']
#
#   Gfactors array format:
#   Col0                |   Col                    |    Gfactor
#   Wavelength (air nm) |   Wavelength (vac nm)    |    J / s / mol
#
#%%%
#Grab the indices corresponding to arbitrary lower and upper bounds; we'll use these to generate a synthetic spectrum.
#These have been chosen to  be just outside the range of the strongest bands:
ind1 = find_nearest_index(gfacs[:,0],256)
ind2 = find_nearest_index(gfacs[:,0],258.5)
xran = np.linspace(257.5,259,10000)
fwhm = 0.01 #in nm; converted to 'sigma' in Gaussian expression internally
thermalized_conv = convolve_spec(xran,gfacs[ind1:ind2,0],gfacs[ind1:ind2,2],fwhm = fwhm)
purefluor_conv = convolve_spec(xran,equilibrium_gfacs[ind1:ind2,0], equilibrium_gfacs[ind1:ind2,2], fwhm=fwhm)
#%
plt.clf()
plt.figure(figsize=(10,10))
plt.plot(thermalized_conv[:,0], thermalized_conv[:,1], label = 'CS Model (Thermalized X1Sigma at T = {:} K)'.format(lte_temp), linestyle='--', color ='red')
plt.plot(purefluor_conv[:,0], purefluor_conv[:,1], label = 'CS Model (Pure Fluorescence, no thermalization)', linestyle='-', color ='black')
plt.legend(fontsize=12)
plt.grid()
plt.xlim(257.5,258.5)
plt.xlabel('Wavelength (nm)', fontsize=16)
plt.ylabel(r'Gfactor (proportional to J/s/mol)', fontsize=16)
plt.savefig('CS_spectrum_thermalized_vs_purefluorescence.png')


